version: '3.8'

services:
  # PostgreSQL container
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cacamaca
      POSTGRES_DB: Studify
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Spring Boot application container
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studify-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Studify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cacamaca
    ports:
      - "8400:8400"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
